version: '3'
services:
  frontend: 
    container_name: frontend
    image: 3205_test/frontend:0.0.1
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
    env_file:
      - ./frontend/.env
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    depends_on:
      - backend
    restart: always

  backend:
    container_name: backend
    image: 3205_test/backend:0.0.1
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: 3205_test/postgres
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - .env  
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always

volumes:
  postgres-data:
  postgres-logs:

 