version: '3'
services:
  backend:
    container_name: backend
    image: pashka1837/backend:0.0.1
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env    
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3000:3000
    restart: always

  frontend: 
    container_name: frontend
    image: pashka1837/frontend:0.0.1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env   
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3001:3001
    depends_on:
      - backend
    restart: always

  

 